repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Mypy Type Check
        entry: mypy
        language: python
        types: [ python ]
        stages: [ commit, push ]
        args: [--strict, --ignore-missing-imports, --allow-subclassing-any]
        additional_dependencies:
          - pytest
          - pydantic
          - neo4j
          - langchain_community
          - langchain_openai

  - repo: local
    hooks:
      - id: ruff-lint
        name: Ruff Lint Check
        entry: poetry run ruff format --check
        language: system
        types: [ python ]
        stages: [ commit, push ]
