repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: ruff-lint-isort
        name: Ruff Lint Sort Imports
        entry: poetry run ruff check .
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: ruff-lint
        name: Ruff Lint Check
        entry: poetry run ruff format --check .
        language: system
        types: [ python ]
        stages: [ commit, push ]
