repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: ruff-lint-isort
        name: Ruff Lint Sort Imports
        entry: uv run ruff check .
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: ruff-lint
        name: Ruff Lint Check
        entry: uv run ruff format --check .
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: mypy
        name: Mypy Type Check
        entry: uv run mypy .
        language: system
        types: [ python ]
        stages: [ commit, push ]
        pass_filenames: false
        args: [
          --strict,
          --ignore-missing-imports,
          --allow-untyped-calls,
          --allow-subclassing-any,
          --exclude='./docs/'
        ]
