name: Publish a new Alpha Major release (0.4.0 -> 1.0.0a0) ðŸš€

on:
  workflow_dispatch:

jobs:
  bump-version:
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PUSH_PAT }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Bump version
        run: uv version --bump major --bump alpha --frozen

      - name: Get version
        id: get-version
        run: echo version=`uv version --short` >> "$GITHUB_OUTPUT"
      - name: Print version
        run: |
          echo Version: ${{ steps.get-version.outputs.version }}
      - name: Update CHANGELOG.md (cross platform supported)
        run: |
          sed -i.bak -e 's/## Next/## Next\n\n## ${{ steps.get-version.outputs.version }}/' CHANGELOG.md && rm CHANGELOG.md.bak
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: 'Neo4j-GraphRAG GitHub Action'
          author_email: 'team-gen-ai@neo4j.com'
          message: 'Bump version to ${{ steps.get-version.outputs.version }}'
          add: "['pyproject.toml', 'CHANGELOG.md']"
          tag: '${{ steps.get-version.outputs.version }}'
